#!/bin/sh
# Emit a GCE `startup-script` that turns a stock instance into a fleet host.
#
# Lab tooling. This is a *generator*, not a second definition: it embeds
# `ecs_host_prepare.sh` verbatim and adds only the two things a startup script
# has to do that a hand-run does not - place the fleet public key, and leave a
# marker saying it finished. Change what a fleet host is by changing
# `ecs_host_prepare.sh`; regenerate afterwards.
#
# Why a startup script rather than a machine image: GCE machine images do not
# support Hyperdisk Balanced, which is the only boot disk C4A instances take. A
# custom image via `gcloud compute images create --source-disk` is the other way
# round it, and either is fine - but the evidence says this one is not worse.
# Two hosts prepared independently by this script came out with all six managed
# files byte-identical and the same 622 packages, and `ecs_host_verify.sh` on
# each host is the gate that would catch divergence rather than assume it away.
# It also keeps a single definition with no image that can drift from it.
#
# The prepare script needs no reboot: `/tmp` is taken off tmpfs live, measured
# on a real instance.
#
# Usage:
#   ./ecs_host_startup_metadata.sh fleet_key.pub > startup.txt
#   gcloud compute instances create vslab-host-0{1..8} \
#       --image-family ubuntu-2604-lts-arm64 --image-project ubuntu-os-cloud \
#       --machine-type c4a-standard-4 --zone ZONE \
#       --metadata-from-file startup-script=startup.txt
#
# GCE runs a startup script on *every* boot, not only the first. That is safe
# here because `ecs_host_prepare.sh` is idempotent and, once the packages are in,
# does not even reach `apt-get update`.

set -eu

KEY_FILE="${1:-}"
if [ -z "${KEY_FILE}" ] || [ ! -f "${KEY_FILE}" ]; then
    echo "usage: $0 <fleet-public-key-file> > startup.txt" >&2
    echo "  the *public* half of the key the fleet manifest's control_endpoint uses" >&2
    exit 64
fi

case "$(cat "${KEY_FILE}")" in
    ssh-*|ecdsa-*|sk-*) ;;
    *) echo "${KEY_FILE} does not look like an ssh public key" >&2; exit 64 ;;
esac
if grep -q "PRIVATE KEY" "${KEY_FILE}"; then
    echo "${KEY_FILE} is a PRIVATE key; pass the .pub half" >&2
    exit 64
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
PREPARE="${HERE}/ecs_host_prepare.sh"
[ -f "${PREPARE}" ] || { echo "cannot find ${PREPARE}" >&2; exit 66; }

REVISION="$(git -C "${HERE}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DIRTY=""
git -C "${HERE}" diff --quiet -- "${PREPARE}" 2>/dev/null || DIRTY=" (uncommitted changes)"

cat <<EOF
#!/bin/sh
# Generated by scripts/ecs_host_startup_metadata.sh from
# scripts/ecs_host_prepare.sh at ${REVISION}${DIRTY}.
# Do not edit here - edit ecs_host_prepare.sh and regenerate.
set -eu

MARKER=/var/lib/valkey-scale-lab-prepared
KEYS_DIR=/etc/ssh/vslab_authorized_keys

exec >>/var/log/valkey-scale-lab-startup.log 2>&1
echo "=== \$(date -Is) startup-script begins (prepare from ${REVISION}) ==="

cat > /root/ecs_host_prepare.sh <<'VSLAB_PREPARE_SCRIPT_EOF'
$(cat "${PREPARE}")
VSLAB_PREPARE_SCRIPT_EOF
chmod 0755 /root/ecs_host_prepare.sh

sh /root/ecs_host_prepare.sh

# The fleet key. Placed here rather than baked into an image so it can be
# rotated by editing metadata, and placed in KEYS_DIR rather than a home
# directory because google-guest-agent rewrites ~/.ssh/authorized_keys from
# metadata and de-provisions the accounts it manages - measured, it revoked a
# hand-placed key within minutes and then deleted the user.
#
# root, because \`sudo\` appears nowhere in the product's runtime/: the backend
# runs every command as the manifest user directly, and those commands write
# under /opt, install iptables chains and read /proc/<pid>/cwd for processes
# they do not own.
install -d -m 755 -o root -g root "\$KEYS_DIR"
cat > "\$KEYS_DIR/root" <<'VSLAB_FLEET_KEY_EOF'
$(cat "${KEY_FILE}")
VSLAB_FLEET_KEY_EOF
chown root:root "\$KEYS_DIR/root"
chmod 644 "\$KEYS_DIR/root"
echo "fleet key placed at \$KEYS_DIR/root"

date -Is > "\$MARKER"

# /tmp off tmpfs, converging in at most one extra boot.
#
# \`ecs_host_prepare.sh\` masks tmp.mount and tries to stop it live, which works
# only when nothing has a file open under /tmp. At first boot something usually
# does, and the mask alone would leave this host running its first gate with
# every node's data directory, RDB and journal in RAM - counted against the very
# MemAvailable the §11.1 sampler reports.
#
# Rebooting is the startup script's business and not the prepare script's: this
# is code that owns the boot, and prepare must never reboot a host someone is
# using. Guarded by its own marker so it can happen at most once, however many
# times GCE re-runs this script.
REBOOTED=/var/lib/valkey-scale-lab-tmp-reboot
if [ "\$(findmnt -no FSTYPE /tmp 2>/dev/null || echo none)" = "tmpfs" ] && [ ! -f "\$REBOOTED" ]; then
    date -Is > "\$REBOOTED"
    echo "=== \$(date -Is) /tmp is still tmpfs; rebooting once to apply the mask ==="
    systemctl reboot
    exit 0
fi

echo "=== \$(date -Is) startup-script complete (/tmp on \$(findmnt -no FSTYPE /tmp 2>/dev/null || echo 'the root filesystem')) ==="
EOF
